### ISSUE TITLE
dryRun and --dry-run does not seem to work as expected 

### ISSUE THREAD

**Issue by haghabozorgi** [estahn/k8s-image-swapper#129]
We are testing the image swapper and have deployed it to our eks cluster, and the dryRun flag does not seem to be working (the actions are still taken; repo is created, image is uploaded, image ref is updated).

When we set the helm chart with 

```
config:
  dryRun: true
  logLevel: debug
  logFormat: console
```
and/or set --dry-run=true as arg in deployment spec the actions are still executed.
