### ISSUE TITLE
Simplify target config

### ISSUE THREAD

**Issue by estahn** [estahn/k8s-image-swapper#25]
Remove the unnecessary nesting in the configuration file:

```yaml
    target:
      registry:
        aws:
          accountId: 123456789
          region: ap-southeast-2
```

to

```yaml
    target:
      aws:
        accountId: 123456789
        region: ap-southeast-2
```
