### ISSUE TITLE
Filters cannot be evaulated

### ISSUE THREAD

**Issue by shaikatz** [estahn/k8s-image-swapper#46]
Hi, trying to setup a basic filter which is very similar to the one in the docs.

Setting:
`jmsepath: "contains(container.image, 'some_repo_prefix')"`

Receiving: 
ERR Filter (idx 0) could not be evaluated. error="SyntaxError: Incomplete expression" filter=

**Comment by estahn** [comment]
@shaikatz Can you provide the entire source section of the config file? `filter=` being empty suggests the configuration file is incorrect.

I just ran the following and the jmespath expression worked fine:
```golang
assert.True(t, filterMatch(filterContext, []config.JMESPathFilter{{JMESPath: "contains(container.image, 'nginx')"}}))
```

In saying all that I realise you have a mistake in the keyword. It's `jmespath` instead of `jmsepath`.

**Comment by shaikatz** [comment]
Thanks for your response @estahn 
Actually, the mistake came from the [docs](https://estahn.github.io/k8s-image-swapper/configuration.html) 😉 

This is the full ConfigMap:
```
apiVersion: v1
data:
  config.yaml: |
    dryRun: true
    logFormat: console
    logLevel: debug
    source:
      filters:
      - jmsepath: contains(container.image, '<MyRealContainerImageName>')
      - jmespath: contains(container.image, '.dkr.ecr.') && contains(container.image,
          '.amazonaws.com')
    target:
      aws:
        accounted: <MyRealAccountId>
        region: <MyRealRegion>
      registry:
        aws:
          accountId: 12345678
          region: ap-southeast-2
      type: aws
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: k8s-image-swapper
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8s-image-swapper
    app.kubernetes.io/version: 1.0.0
    argocd.argoproj.io/instance: k8s-image-swapper
    helm.sh/chart: k8s-image-swapper-0.2.4
  name: k8s-image-swapper
  namespace: infrastructure

```

Replaced sensitive data with <> text.
