### ISSUE TITLE
aws encryptionConfiguration not being set with KMS

### ISSUE THREAD

**Issue by bdjtcg** [estahn/k8s-image-swapper#598]
I am trying to enable KMS encryption and have set the following in the config, however repositories are still being created with AES-256. :
```
target:
  aws:
    accountId: "123456"
    ecrOptions:
      encryptionConfiguration:
        encryptionType: "KMS"
        kmsKey: "arn:aws:kms:us-west-2:123456"
    region: us-west-2

```
No errors are logged. Please let me know if anyone has successfully set kms encryption. Any help is appreciated.
Also, I noticed there is no reference to encryptionConfiguration in the [ecr.go.80](https://github.com/estahn/k8s-image-swapper/blob/12f6bb7c25307c436945725b7eb82521fd163466/pkg/registry/ecr.go#L80C1-L89C3):

```
client := &ECRClient{
		client:          ecrClient,
		ecrDomain:       ecrDomain,
		cache:           cache,
		scheduler:       scheduler,
		targetAccount:   clientConfig.AccountID,
		accessPolicy:    clientConfig.ECROptions.AccessPolicy,
		lifecyclePolicy: clientConfig.ECROptions.LifecyclePolicy,
		tags:            clientConfig.ECROptions.Tags,
	}
```
