### ISSUE TITLE
AWS Support target "repository" as a prefix

### ISSUE THREAD

**Issue by ryanfaircloth** [estahn/k8s-image-swapper#640]
currently images are pushed to ecr in /docker.io/ syntax in some cases where multiple eks clusters are in the same account in the same region but may not share authorized images a parent repository path is appropriate add a prefix to the aws target config and prepend the value to the target path to ensure separation as needed

**Comment by estahn** [comment]
@ryanfaircloth Interesting. Why would you want to separate those, as they would be identical?

**Comment by ryanfaircloth** [comment]
Without the prefix it's possible to trick image swapper into pulling a malicious image from another registry with the same name

**Comment by estahn** [comment]
@ryanfaircloth I'm just discussing some mechanics to change the source image in #660 and wondered if that could be useful in your case as well, but on the `target` end:

```yaml
source:
  filters:
  - jmespath: "contains(container.image, '.dkr.ecr.') && contains(container.image, '.amazonaws.com')"

  preprocessor:
  - replace:
       from: dkr.ecr.eu-west-1.amazonaws.com
       to: dkr.ecr.us-east-1.amazonaws.com
```

In your case it's probably something like:

```yaml
source:
  filters:
  - jmespath: "contains(container.image, '.dkr.ecr.') && contains(container.image, '.amazonaws.com')"

  preprocessor:
  - prefix: <myprefix>

target:
  preprocessor:
  - prefix: <myprefix>

```

Thoughts?

**Comment by ryanfaircloth** [comment]
I think this could work

**Comment by hclaria** [comment]
Hello! Thank you for providing this awesome app :)

We were interested in trying and using the prefix feature, however ; 
`target.aws.prefix` doesn't work with an ECR target (tested 1.6.5): the repo it creates and the path it pushes to diverge — so it can't be used for least-privilege IAM, which is the point of this issue.

Config:
```yaml
config:
  target:
    type: aws
    aws:
      accountId: "<ACCOUNT_ID>"
      region: <REGION>
      prefix: /k8s-image-swapper
```

IAM, scoped to the prefix (the natural least-privilege setup):
```json
{
  "Version": "2012-10-17",
  "Statement": [
    { "Effect": "Allow",
      "Action": ["ecr:GetAuthorizationToken","ecr:DescribeRepositories","ecr:DescribeRegistry","ecr:TagResource"],
      "Resource": "*" },
    { "Effect": "Allow",
      "Action": ["ecr:CreateRepository","ecr:BatchCheckLayerAvailability","ecr:BatchGetImage","ecr:CompleteLayerUpload","ecr:GetDownloadUrlForLayer","ecr:InitiateLayerUpload","ecr:ListImages","ecr:PutImage","ecr:PutLifecyclePolicy","ecr:PutImageScanningConfiguration","ecr:UploadLayerPart"],
      "Resource": "arn:aws:ecr:<REGION>:<ACCOUNT_ID>:repository/k8s-image-swapper/*" }
  ]
}
```

Error (account/region/session redacted):
```
ERR image copy error while creating a new repository in target registry error="AccessDeniedException: 
User: arn:aws:sts::<ACCOUNT_ID>:assumed-role/k8s-image-swapper/<SESSION> is not authorized to perform: ecr:CreateRepository on resource: arn:aws:ecr:<REGION>:<ACCOUNT_ID>:repository/docker.io/library/alpine 
because no identity-based policy allows the ecr:CreateRepository action" namespace=default source-image=docker.io/library/alpine:3.19 target-image=<ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/k8s-image-swapper/docker.io/library/alpine:3.19
```

`target-image` carries the prefix, but `CreateRepository` is called for `docker.io/library/alpine` (no prefix). `EcrDomain()` adds the prefix to the push target, while `image_copier.go` names the repo from the source ref:
```go
createRepoName := reference.TrimNamed(ic.sourceImageRef.DockerReference()).String() // "docker.io/library/alpine"
```
So the prefix-scoped policy denies it. Even with `repository/*`, the push then targets `<prefix>/docker.io/library/alpine`, which was never created (ECR doesn't auto-create on push). For ECR, `createRepoName` would need to derive from the target ref.
